services:
  vaultwarden:
    image: vaultwarden/server:1.30.5
    user: "1000:1000"
    environment:
      SIGNUPS_ALLOWED: 'false'
    volumes:
      - ./data:/data
    ports:
      - 8080:80
    restart: unless-stopped
